#!/usr/bin/env ksh
#
# Description:	Try to infer the MIME type of a file by its extension
#		(and in a few cases, from its name)
# Author:	René Uittenbogaard
# Date:		2019-03-27
# Usage:	mime-identify <filename>
#		OR
#		source mime-identify; f_mime_identify <filename>
#
# Some web locations from which MIME types were taken:
#
# - https://svn.apache.org/repos/asf/httpd/httpd/trunk/docs/conf/mime.types
# - https://www.digipres.org/formats/mime-types/
# - https://www.sitepoint.com/mime-types-complete-list/
# - https://help.dreamhost.com/hc/en-us/articles/216736088-MIME-Types
#

############################################################################
# functions

f_mime_identify() {
	filename="$1"

	case "$(echo ${filename##*.} | tr A-Z a-z)" in
		1m)		echo a text/nroff				;;
		3gp)		echo b video/3gpp				;;
		3i)		echo a application/x-intercal			;;
		3pm)		echo a text/nroff				;;
		7z)		echo b application/x-7z-compressed		;;
		[1-8])		echo a text/nroff				;;
		a)		echo b application/x-unix-archive		;;
		a[0-9][0-9])	echo b application/arj				;;
		ac)		echo a text/x-autoconf				;;
		ai)		echo b application/postscript			;;
		aif)		echo b audio/x-aiff				;;
		aifc)		echo b audio/x-aiff				;;
		aiff)		echo b audio/x-aiff				;;
		am)		echo a text/x-autoconf				;;
		apk)		echo b application/vnd.android.package-archive	;;
		ar)		echo b application/x-unix-archive		;;
		arc)		echo b application/x-arc			;;
		arj)		echo b application/arj				;;
		asf)		echo b video/x-ms-asf				;;
		asr)		echo b video/x-ms-asf				;;
		asx)		echo b video/x-ms-asf				;;
		au)		echo b audio/basic				;;
		avi)		echo b video/x-msvideo				;;
		awk)		echo a text/x-awk				;;
		bas)		echo a text/x-bas				;;
		bash)		echo a text/x-bash				;;
		bat)		echo a text/x-msdos-batch			;;
		bf)		echo a application/x-befunge			;;
		bin)		echo b application/octet-stream			;;
		bmp)		echo b image/bmp				;;
		bz)		echo b application/x-bzip			;;
		bz2)		echo b application/x-bzip2			;;
		c)		echo a text/x-c					;;
		c++)		echo a text/x-c++				;;
		cab)		echo b application/x-cab-compressed		;;
		cc)		echo a text/x-c++				;;
		cer) 		echo a application/x-x509-ca-cert		;;
		class)		echo b application/octet-stream			;;
		cmd)		echo a text/x-msdos-batch			;;
		com)		echo b application/octet-stream			;;
		cpio)		echo b application/x-cpio			;;
		cpp)		echo a text/x-c++				;;
		crt) 		echo a application/x-x509-ca-cert		;;
		cs)		echo a text/x-csharp				;;
		csh)		echo a text/x-csh				;;
		css)		echo a text/css					;;
		deb)		echo b application/x-deb			;;
		der) 		echo a application/x-x509-ca-cert		;;
		dia)		echo b application/x-dia-diagram		;;
		dll)		echo b application/octet-stream			;;
		doc)		echo b application/msword			;;
		docx)		echo b application/msword			;;
		dot)		echo b application/msword			;;
		dvi)		echo b application/x-dvi			;;
		elm)		echo a application/x-elm			;;
		eml)		echo a message/rfc822				;;
		eot)		echo b application/vnd.ms-fontobject		;;
		eps)		echo b application/postscript			;;
		epub)		echo b application/epub+zip			;;
		exe)		echo b application/octet-stream			;;
		f)		echo a text/x-fortran				;;
		f4v)		echo b video/x-f4v				;;
		f77)		echo a text/x-fortran				;;
		f90)		echo a text/x-fortran				;;
		f95)		echo a text/x-fortran				;;
		flac)		echo b video/x-flac				;;
		flc)		echo b video/x-flac				;;
		fli)		echo b video/x-fli				;;
		flv)		echo b video/x-flv				;;
		for)		echo a text/x-fortran				;;
		gif)		echo b image/gif				;;
		gz)		echo b application/x-gzip			;;
		h)		echo a text/x-c					;;
		hh)		echo a text/plain				;;
		hlp)		echo b application/x-winhelp			;;
		hqx)		echo b application/mac-binhex40			;;
		htm)		echo a text/html				;;
		html)		echo a text/html				;;
		i)		echo a application/x-intercal			;;
		ico)		echo b image/x-icon				;;
		iges)		echo b model/ige				;;
		igs)		echo b model/ige				;;
		in)		echo a text/x-autoconf				;;
		ini)		echo a text/plain				;;
		jar)		echo b application/java-archive			;;
		java)		echo a text/x-java				;;
		jfif)		echo b image/jpeg				;;
		jpe)		echo b image/jpeg				;;
		jpeg)		echo b image/jpeg				;;
		jpg)		echo b image/jpeg				;;
		jpm)		echo b image/jpm				;;
		js)		echo a application/javascript			;;
		json)		echo a application/json				;;
		ksh)		echo a text/x-ksh				;;
		latex)		echo a application/x-latex			;;
		lha)		echo b application/x-lzh-compressed		;;
		log)		echo a text/plain				;;
		lsp)		echo a application/x-lisp			;;
		lzh)		echo b application/x-lzh-compressed		;;
		m1v)		echo b video/mpeg				;;
		m2a)		echo b audio/mpeg				;;
		m2v)		echo b video/mpeg				;;
		m3a)		echo b audio/mpeg				;;
		m3u)		echo b audio/x-mpegurl				;;
		m3u8)		echo b application/vnd.apple.mpegurl		;;
		m4a)		echo b audio/mp4				;;
		m4v)		echo b video/x-m4v				;;
		man)		echo a text/troff				;;
		md)		echo a text/markdown				;;
		mdb)		echo b application/x-msaccess			;;
		me)		echo a text/troff				;;
		mesh)		echo b model/mesh				;;
		mht)		echo a message/rfc822				;;
		mhtm)		echo a message/rfc822				;;
		mhtml)		echo a message/rfc822				;;
		mid)		echo b audio/midi				;;
		midi)		echo b audio/midi				;;
		mjs)		echo a application/javascript			;;
		mk3d)		echo b video/x-matroska				;;
		mka)		echo b audio/x-matroska				;;
		mks)		echo b video/x-matroska				;;
		mkv)		echo b video/x-matroska				;;
		mm)		echo a text/troff				;;
		mng)		echo b video/x-mng				;;
		mov)		echo b video/quicktime				;;
		movie)		echo b video/x-sgi-movie			;;
		mp2)		echo b video/mpeg				;;
		mp2a)		echo b audio/mpeg				;;
		mp3)		echo b audio/mpeg				;;
		mp4)		echo b video/mp4				;;
		mp4a)		echo b audio/mp4				;;
		mp4v)		echo b video/mp4				;;
		mpa)		echo b video/mpeg				;;
		mpc)		echo b application/x-project			;;
		mpe)		echo b video/mpeg				;;
		mpeg)		echo b video/mpeg				;;
		mpg)		echo b video/mpeg				;;
		mpg4)		echo b video/mp4				;;
		mpga)		echo b audio/mpeg				;;
		mpkg)		echo b application/vnd.apple.installer+xml	;;
		mpp)		echo b application/vnd.ms-project		;;
		ms)		echo a text/troff				;;
		msh)		echo b model/mesh				;;
		news)		echo a message/rfc822				;;
		nl)		echo a text/plain				;;
		nws)		echo a message/rfc822				;;
		odp)		echo b application/x-openoffice			;;
		ods)		echo b application/x-openoffice			;;
		odt)		echo b application/x-openoffice			;;
		oga)		echo b audio/ogg				;;
		ogg)		echo b application/ogg				;;
		ogm)		echo b application/ogg				;;
		ogv)		echo b video/ogg				;;
		ogx)		echo b application/ogg				;;
		p)		echo a application/x-chem			;;
		p10)		echo b application/pkcs10			;;
		p12)		echo b application/pkcs12			;;
		p7b)		echo b application/pkcs7-certificates		;;
		p7c)		echo b application/pkcs7-mime			;;
		p7m)		echo b application/pkcs7-mime			;;
		p7r)		echo b application/pkcs7-certreqresp		;;
		p7s)		echo b application/pkcs7-signature		;;
		pas)		echo a text/x-pascal				;;
		pbm)		echo b image/x-portable-bitmap			;;
		pct)		echo b image/pict				;;
		pcx)		echo b image/x-pcx				;;
		pdb)		echo a chemical/x-pdb				;;
		pdf)		echo b application/pdf				;;
		pem) 		echo a application/x-pem-file			;;
		pfx)		echo b application/pkcs12			;;
		pgm)		echo b image/x-portable-graymap			;;
		php)		echo a text/x-php				;;
		phtml)		echo a text/x-php				;;
		pic)		echo b image/pict				;;
		pict)		echo b image/pict				;;
		pkg)		echo b application/x-pkg			;;
		pl)		echo a text/x-perl				;;
		planner)	echo b application/x-planner			;;
		pm)		echo a text/x-perl-module			;;
		png)		echo b image/png				;;
		pnm)		echo b image/x-portable-anymap			;;
		pot)		echo b application/vnd.ms-powerpoint		;;
		pov)		echo a model/x-pov				;;
		ppm)		echo b image/x-portable-pixmap			;;
		pps)		echo b application/vnd.ms-powerpoint		;;
		ppt)		echo b application/vnd.ms-powerpoint		;;
		pptx)		echo b application/vnd.ms-powerpoint		;;
		ps)		echo b application/postscript			;;
		py)		echo a text/x-python				;;
		qt)		echo b video/quicktime				;;
		r[0-9][0-9])	echo b application/x-rar-compressed		;;
		ra)		echo b audio/x-realaudio			;;
		ram)		echo b audio/x-pn-realaudio			;;
		rar)		echo b application/x-rar-compressed		;;
		rm)		echo b audio/x-pn-realaudio			;;
		rmi)		echo b audio/midi				;;
		roff)		echo a text/troff				;;
		rpm)		echo b application/x-rpm			;;
		rss)		echo b application/rss+xml			;;
		rtf)		echo b application/rtf				;;
		rtx)		echo a text/richtext				;;
		sass)		echo a text/x-sass				;;
		scm)		echo a application/x-scheme			;;
		scss)		echo a text/x-scss				;;
		sgm)		echo a text/sgml				;;
		sgml)		echo a text/sgml				;;
		sh)		echo a text/x-sh				;;
		shar)		echo a application/x-shar			;;
		shtml)		echo a text/html				;;
		silo)		echo b model/mesh				;;
		sit)		echo b application/x-stuffit			;;
		sl)		echo b application/octet-stream			;;
		smi)		echo b application/smil				;;
		smil)		echo b application/smil				;;
		smv)		echo b video/x-smv				;;
		snd)		echo b audio/basic				;;
		so)		echo b application/octet-stream			;;
		spc)		echo b application/pkcs7-certificates		;;
		spl)		echo b application/x-futuresplash		;;
		sql)		echo a text/x-sql				;;
		srp)		echo b application/x-rationalplan		;;
		ss)		echo a application/x-scheme			;;
		stm)		echo a text/html				;;
		sty)		echo a text/x-tex-style				;;
		svg)		echo b image/svg+xml				;;
		svgz)		echo b image/svg+xml				;;
		swf)		echo b application/x-shockwave-flash		;;
		t)		echo a text/troff				;;
		tar)		echo b application/x-tar			;;
		taz)		echo b application/x-tar-compress		;;
		tbz2)		echo b application/x-tar-bzip2			;;
		tcsh)		echo a text/x-tcsh				;;
		tex)		echo a application/x-tex			;;
		texi)		echo a application/x-texinfo			;;
		texinfo)	echo a application/x-texinfo			;;
		tga)		echo b image/x-targa				;;
		tgz)		echo b application/x-tar-gzip			;;
		tif)		echo b image/tiff				;;
		tiff)		echo b image/tiff				;;
		torrent)	echo b application/x-bittorrent			;;
		tpl)		echo a text/plain				;;
		tpu)		echo b application/x-tpu			;;
		tr)		echo a text/troff				;;
		ts)		echo a application/x-typescript			;;
		ts)		echo b video/mp2t				;; # duplicate
		tsx)		echo a application/x-typescript			;;
		ttf)		echo a font/ttf					;;
		txt)		echo a text/plain				;;
		tz)		echo b application/x-tar-compress		;;
		uml)		echo b application/x-uml			;;
		uu)		echo a text/x-uuencode				;;
		uue)		echo a text/x-uuencode				;;
		vba)		echo a text/x-vimball				;;
		vcf)		echo a text/x-vcard				;;
		vcs)		echo a text/x-vcalendar				;;
		vim)		echo a text/x-vim				;;
		viv)		echo b video/vnd.vivo				;;
		vivo)		echo b video/vnd.vivo				;;
		vob)		echo b video/x-ms-vob				;;
		voc)		echo b audio/x-voc				;;
		vrml)		echo b model/vrml				;;
		wav)		echo b audio/x-wav				;;
		wcm)		echo b application/vnd.ms-works			;;
		wdb)		echo b application/vnd.ms-works			;;
		webm)		echo b video/webm				;;
		webp)		echo b image/webp				;;
		wks)		echo b application/vnd.ms-works			;;
		wm)		echo b video/x-ms-wm				;;
		wmv)		echo b video/x-winmedia				;;
		wmx)		echo b video/x-ms-wmx				;;
		woff)		echo b font/woff				;;
		woff2)		echo b font/woff2				;;
		wp)		echo b application/wordperfect			;;
		wp5)		echo b application/wordperfect			;;
		wp6)		echo b application/wordperfect			;;
		wps)		echo b application/vnd.ms-works			;;
		wri)		echo b application/msword			;;
		wrl)		echo b model/vrml				;;
		wvx)		echo b video/x-ms-wvx				;;
		xbm)		echo b image/x-xbitmap				;;
		xcf)		echo b image/x-gimp				;;
		xhtml)		echo a application/xhtml+xml			;;
		xif)		echo b image/vnd.xiff				;;
		xla|xlc|xld)	echo b application/vnd.ms-excel			;;
		xlk|xll|xlm)	echo b application/vnd.ms-excel			;;
		xlsx)		echo b application/vnd.ms-excel			;;
		xls|xlt|xlv)	echo b application/vnd.ms-excel			;;
		xlw)		echo b application/vnd.ms-excel			;;
		xml)		echo a application/xml				;;
		xpm)		echo b image/x-xpixmap				;;
		xwd)		echo b image/x-xwindowdump			;;
		xyz)		echo a chemical/x-xyz				;;
		yenc)		echo b application/x-yenc-encoded		;;
		yml)		echo a application/x-yaml			;;
		ync)		echo b application/x-yencoded			;;
		yuv)		echo b video/x-oggyuv				;;
		z)		echo b application/x-compress			;;
		zip)		echo b application/zip				;;
		zoo)		echo b application/x-zoo			;;
		zsh)		echo a text/x-zsh				;;
		# individual files
		makefile)	echo a text/x-makefile				;;
		dockerfile)	echo a text/x-dockerfile			;;
		*)		echo b default					;;
	esac
}

############################################################################
# For direct invocation

test "$1" && f_mime_identify "$1" || true

